### ISSUE TITLE
Resolution of cross references doesn't work in special row combination

### ISSUE THREAD

**Issue by sparsick** [cologneintelligence/FitGoodies#24]
Given following expected table with cross references throws `NumberFormatException` :

x (String)| y (int) | z (int)
-----------|----------|---------
x| ${test} | 3
x| 5 | 6|

The computed table looks

x (String)| y (int) | z (int)
-----------|----------|---------
x| 2 | 3
x| 5 | 6

The reason for the exception is that the original `RowFixture` tries to use `${test}` as key and parsing to `int` fails.

**Comment by jochenwierum** [comment]
Fixed by #25
