### ISSUE TITLE
Differentiation of boolean datatypes from other datatypes

### ISSUE THREAD

**Issue by Kaucher90** [cologneintelligence/FitGoodies#41]
for boolean variables, only the string "true" will be parsed to the boolean value true. If the tester puts some other, maybe context related String like "ok" into the variable, he will NOT get an parse error. Fit just parses it to false.

There should be two determined strings/codes to map the boolen values true and false, exception otherwise.

**Comment by jochenwierum** [comment]
In the current Version of fitgoodies, parsing boolean values is not implemented. We should throw an error in this case (instead, the column stays ```null```).

When it comes to comparing, fit just uses ```toString``` and compares the result. I see three tasks here:

* throw an error if an asignment is not supported
* support booleans in asignments
* check if it is possible to support booleans as a method return value more propertly
